name: Deploy to Azure VM

on:
  workflow_run:
    workflows: ["Node.js CI"]   # 👈 build workflow name likho yahan
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact from previous workflow
        uses: dawidd6/action-download-artifact@v11
        with:
          name: todo-ui-build-artifact
          path: ./build
          run_id: ${{ github.event.workflow_run.id }}

      # - name: Copy files to Azure VM
      #   uses: appleboy/scp-action@v0.1.5
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     port: ${{ secrets.PORT }}
      #     script: whoami
      #     source: "build/*"
      #     target: "/var/www/html"

      # - name: Restart Nginx
      #   uses: appleboy/ssh-action@v0.1.10
      # - name: Copy files to Azure VM
      #   uses: appleboy/scp-action@v0.1.5
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       sudo systemctl restart nginx
      - name: Copy files to temp folder
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "build/*"
          target: "/home/${{ secrets.AZURE_VM_USER }}/build"
            
      - name: Move files to Nginx root
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo mv /home/${{ secrets.USERNAME }}/build/* /var/www/html/
            sudo systemctl restart nginx
            
